# training configs
pt: 1p5
hitgraph: geometric
input_dir: /global/cfs/cdirs/m3443/usr/ameyat/hitgraphs/
lr: 0.001
epochs: 200
step_size: 5
gamma: 0.7
batch_size: 18
test_batch_size: 1

# model configs
n_input: 3
n_hidden: 8
n_layers: 3
n_graph_iters: 5
n_output: 1
c_weight: 0.005
equi_output: True
vector_dim: 2
hidden_activation: SiLU
layernorm: True 
batchnorm: False